services:
  db:
    image: postgres:15-alpine
    container_name: hw12_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_app_net

  redis:
    image: redis:7-alpine
    container_name: hw12_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal_app_net
    restart: always

  app:
    build: .
    container_name: hw12_fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - internal_app_net

volumes:
  postgres_data:
  redis_data:

networks:
  internal_app_net:
    driver: bridge
