import logging
import asyncio
from pathlib import Path
from typing import Optional

from fastapi_mail import FastMail, MessageSchema, ConnectionConfig, MessageType
from fastapi_mail.errors import ConnectionErrors
from pydantic import EmailStr, NameEmail

from src.services.auth import create_email_token
from src.config.app_config import settings

logger = logging.getLogger(__name__)

# Визначаємо абсолютний шлях до папки з шаблонами
TEMPLATE_DIR = Path(__file__).parent / "templates"

# Конфігурація підключення до поштового сервера
email_conf = ConnectionConfig(
    MAIL_USERNAME=settings.MAIL_USERNAME,
    MAIL_PASSWORD=settings.MAIL_PASSWORD,
    MAIL_FROM=settings.MAIL_FROM,
    MAIL_PORT=settings.MAIL_PORT,
    MAIL_SERVER=settings.MAIL_SERVER,
    MAIL_FROM_NAME=settings.MAIL_FROM_NAME,
    MAIL_STARTTLS=settings.MAIL_STARTTLS,
    MAIL_SSL_TLS=settings.MAIL_SSL_TLS,
    USE_CREDENTIALS=settings.USE_CREDENTIALS,
    VALIDATE_CERTS=settings.VALIDATE_CERTS,
    TEMPLATE_FOLDER=TEMPLATE_DIR,
)


async def send_admin_alert(error_details: str):
    """
    Термінове сповіщення адміністратора про технічні несправності сервісу.
    Використовує простий текст для максимальної надійності.
    """
    try:
        admin_recipient = NameEmail(name="System Admin", email=settings.ADMIN_EMAIL)
        message = MessageSchema(
            subject="[SYSTEM ALERT] Email Service Failure",
            recipients=[admin_recipient], 
            body=f"Technical alert generated by API:\n\n{error_details}",
            subtype=MessageType.plain,
        )
        fm = FastMail(email_conf)
        await fm.send_message(message)
    except Exception as e:
        logger.critical(f"CRITICAL: Failed to notify admin about error: {e}")


async def _send_email_base(
    email: EmailStr,
    username: str,
    subject: str,
    template_name: str,
    template_context: dict,
) -> bool:
    """
    Базова функція відправки.
    Якщо HTML-шаблон відсутній, автоматично відправляє текстову заглушку
    та сповіщає адміністратора про проблему.
    """
    try:
        fm = FastMail(email_conf)
        template_path = TEMPLATE_DIR / template_name

        # --- СЦЕНАРІЙ 1: Шаблон відсутній (Fallback) ---
        if not template_path.exists():
            error_log = f"Template '{template_name}' missing in {TEMPLATE_DIR}."
            logger.error(error_log)

            # Сповіщаємо адміна у фоновому режимі, щоб не затримувати користувача
            asyncio.create_task(send_admin_alert(f"{error_log}\nTarget user: {email}"))

            # Формуємо текстову заглушку
            token = template_context.get("token", "N/A")
            host = template_context.get("host", "#")
            body = (
                f"Hello {username}!\n\n"
                f"Please use the following link for {subject}:\n"
                f"{host}/api/auth/confirm/{token}\n\n"
                f"If you didn't request this, please ignore this email."
            )

            message = MessageSchema(
                subject=f"{subject} (Security Link)",
                recipients=[NameEmail(name=username, email=email)],
                body=body,
                subtype=MessageType.plain,
            )
            await fm.send_message(message)
            logger.info(
                f"Fallback plain-text email sent to {email} due to missing template."
            )
            return True

        # --- СЦЕНАРІЙ 2: Все добре, відправляємо HTML ---
        message = MessageSchema(
            subject=subject,
            recipients=[NameEmail(name=username, email=email)],
            template_body=template_context,
            subtype=MessageType.html,
        )
        await fm.send_message(message, template_name=template_name)
        logger.info(f"HTML email '{subject}' successfully sent to {email}")
        return True

    except ConnectionErrors as err:
        logger.error(f"Connection error while sending to {email}: {err}")
    except Exception as err:
        logger.error(f"Unexpected error for {email}: {err}", exc_info=True)

    return False


async def send_verification_email(email: EmailStr, username: str, host: str):
    """Публічний метод для верифікації нового користувача"""
    token = create_email_token({"sub": email})
    context = {
        "host": host,
        "username": username,
        "token": token,
    }
    await _send_email_base(
        email=email,
        username=username,
        subject="Confirm your email address",
        template_name="verify_email.html",
        template_context=context,
    )


async def send_reset_password_email(email: EmailStr, username: str, host: str):
    """Публічний метод для скидання пароля"""
    token = create_email_token({"sub": email})
    context = {
        "host": host,
        "username": username,
        "token": token,
    }
    await _send_email_base(
        email=email,
        username=username,
        subject="Password Reset Request",
        template_name="reset_password.html",
        template_context=context,
    )
