"""add to model User filed confirmed

Revision ID: 002869cf0761
Revises: be12831008ae
Create Date: 2026-04-28 20:10:14.235556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "002869cf0761"
down_revision: Union[str, Sequence[str], None] = "be12831008ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column("users", sa.Column("confirmed", sa.Boolean(), nullable=True))

    # 2. Update existing records
    op.execute("UPDATE users SET confirmed = False")

    # 3. Set NOT NULL
    op.alter_column("users", "confirmed", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    # ### end Alembic commands ###
